browser=chrome-headless
emailid=vinayadapa7777@gmail.com
password=Ashokadapa333@
emailid1=rajeswariramu98@gmail.com
password1=Raji@123
userName=Vinay Adapa
userName1=Nallavala Rajeswari
url=https://www.naukri.com/
ReportName=Naukri test Results
DocumentTitle=Naukri Test
TesterName=UATTester
